### PR TITLE
Update to 0.8.3

### PR DESCRIPTION
**Pull request by jan-janssen**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by jan-janssen** [comment]
@conda-forge/core Can one of you merge this pull request? Pull requests have been open on this recipe for over a year https://github.com/conda-forge/terracotta-feedstock/pull/16 . In this pull request, I am adding myself as maintainer, to keep the recipe up to date in the future.

**Comment by ocefpaf** [comment]
We usually wait for ~ 1 week for the maintainers to respond. However, the mxr-conda team is MIA so I'm opening an exception here.

**Pull request merged**
